### ISSUE TITLE
GET /devices/json  - - TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by wenpq** [dongliu/traveler#31]
It show error when I click add <Add devices> on traveler config page. 

`GET /bootstrap-datepicker/dist/js/bootstrap-datepicker/dist.js 404 1.479 ms - 70
TypeError: Cannot read property 'url' of undefined
    at /home/wenpq/Desktop/traveler/distribution/routes/device.js:14:26
    at Layer.handle [as handle_request] (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/route.js:131:13)
    at ensureAuthenticated (/home/wenpq/Desktop/traveler/distribution/lib/auth.js:65:5)
    at Layer.handle [as handle_request] (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/layer.js:95:5)
    at /home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/index.js:330:12)
    at next (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/index.js:312:13)
    at /home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/index.js:330:12)
    at next (/home/wenpq/Desktop/traveler/distribution/node_modules/express/lib/router/index.js:271:10)
GET /devices/json 500 2.039 ms - -
`

**Comment by dongliu** [comment]
Fixed in commit c0ac9300e5a782f919003bd9028a8e23f5a948e2
